import type { AIModel } from './db';

export const DEFAULT_MODELS: AIModel[] = [
  {
    id: 'claude-opus-4',
    name: 'Claude Opus 4.6',
    provider: 'Anthropic',
    description: 'Most capable model for complex analysis, coding, math, and creative writing. Extended thinking with step-by-step reasoning. State-of-the-art performance across all benchmarks.',
    parameters: '2T',
    size: '5.2 GB',
    sizeBytes: 5582061568,
    capabilities: ['Code Generation', 'Advanced Reasoning', 'Creative Writing', 'Vision', 'Tool Use', 'Extended Thinking', 'Agentic Tasks'],
    logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpFdyVpVeiHpaCdE4FL2M9YJZRPU-wbWgqRQ&s',
    downloaded: false,
    downloadProgress: 0,
    version: '4.6.0',
    quantization: 'Q4_K_M',
    contextWindow: '200K',
    architecture: 'Transformer (Constitutional AI)'
  },
  {
    id: 'chatgpt-5',
    name: 'ChatGPT-5',
    provider: 'OpenAI',
    description: 'Next-generation multimodal model with native image, audio, and code understanding. Enhanced reasoning capabilities and massive context window for complex tasks.',
    parameters: '1.8T',
    size: '4.8 GB',
    sizeBytes: 5153960755,
    capabilities: ['Multimodal', 'Code Interpreter', 'DALL-E Integration', 'Browsing', 'Plugins', 'Voice', 'Advanced Data Analysis'],
    logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl4ME17pNVHlQNwiw3IrqL6f-4tE2X05UjUw&s',
    downloaded: false,
    downloadProgress: 0,
    version: '5.0.0',
    quantization: 'Q4_K_M',
    contextWindow: '128K',
    architecture: 'GPT (Generative Pre-trained Transformer)'
  },
  {
    id: 'gemini-25-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google DeepMind',
    description: 'Most capable Gemini model with 1M token context. Excels at long-document analysis, multimodal reasoning, and complex code generation across all major languages.',
    parameters: '1.56T',
    size: '4.5 GB',
    sizeBytes: 4831838208,
    capabilities: ['1M Context', 'Multimodal', 'Code Generation', 'Scientific Reasoning', 'Video Understanding', 'Grounding', 'Function Calling'],
    logoUrl: 'https://www.dztecs.com/ai/wp-content/uploads/sites/2/2025/09/gHfBJ6FBHKnLbW36hEDvgV.png',
    downloaded: false,
    downloadProgress: 0,
    version: '2.5.0',
    quantization: 'Q4_K_M',
    contextWindow: '1M',
    architecture: 'Mixture of Experts (MoE)'
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'DeepSeek',
    description: 'Open-source reasoning model rivaling top proprietary models. Exceptional at math, coding, and logical reasoning with transparent chain-of-thought process.',
    parameters: '671B',
    size: '3.8 GB',
    sizeBytes: 4080218931,
    capabilities: ['Open Source', 'Chain of Thought', 'Math', 'Coding', 'Logical Reasoning', 'Self-Reflection', 'Multi-step Problem Solving'],
    logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ09ekt850mXs23iTiP82moDbKzJdECTnmv-g&s',
    downloaded: false,
    downloadProgress: 0,
    version: '1.0.0',
    quantization: 'Q4_K_M',
    contextWindow: '64K',
    architecture: 'Mixture of Experts (MoE)'
  }
];
